# prom-cert.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prom-tls
  namespace: monitoring
spec:
  secretName: prom-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod      # change to your issuer
  dnsNames:
    - prom.gnzaga.com

