#!/bin/bash

# Script to combine all media server stack files into a single file
# This is useful for sharing with LLMs for planning and efficiency analysis

OUTPUT_FILE="full-media-stack.yml"
HEADER_FILE="media-stack-header.txt"

# Create header with information about the combined file
cat > "$HEADER_FILE" << EOL
# COMBINED MEDIA SERVER STACK
# This file is automatically generated by combine-stacks.sh
# It combines all individual stack files for analysis purposes
# DO NOT USE THIS FILE FOR DEPLOYMENT - use the individual stack files instead
#
# Generated on: $(date)
# Combined from:
#  - jelly-stack.yml (Jellyfin media server and request management)
#  - arr-stack.yml (Media management services - Sonarr, Radarr, etc.)
#  - media-download.yml (VPN tunnel and download clients)
#
# This combined file is intended for planning and analysis by LLMs
# to suggest efficiency improvements or configuration changes.

EOL

# Start with version and services
echo "version: \"3.8\"" > "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "services:" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Function to extract services from a compose file and add them to the output
extract_services() {
    local file=$1
    local stack_name=$2
    
    echo "Processing $stack_name from $file..."
    
    # Skip the version and services line, and extract all service definitions
    sed -n '/^services:/,$ p' "$file" | tail -n +2 >> "$OUTPUT_FILE"
    
    # Add a separator between stacks
    echo "" >> "$OUTPUT_FILE"
    echo "  # ----------------------------------------" >> "$OUTPUT_FILE"
    echo "  # End of $stack_name services" >> "$OUTPUT_FILE"
    echo "  # ----------------------------------------" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
}

# Process each stack file
extract_services "jelly-stack.yml" "Jellyfin Media Server Stack"
extract_services "arr-stack.yml" "Media Management Stack"
extract_services "media-download.yml" "Media Download Stack"

# Insert the header at the beginning of the file
cat "$HEADER_FILE" "$OUTPUT_FILE" > temp.yml && mv temp.yml "$OUTPUT_FILE"

# Remove the temporary header file
rm "$HEADER_FILE"

echo "Combined stack file created at $OUTPUT_FILE"
echo "This file contains all services from your media server stacks for analysis purposes."
echo "Remember: DO NOT use this file for deployment - use the individual stack files instead."