global:
  image:
    tag: v2.11.0

server:
  service:
    type: LoadBalancer
    # loadBalancerIP: 192.168.42.106  # optional: reserve with MetalLB
  extraArgs:
    - --insecure

applicationSet:
  enabled: true

configs:
  cm:
    admin.enabled: "true"
  params:
    server.insecure: "true"

