apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-website
  namespace: portfolio
  labels:
    app: portfolio-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-website
  template:
    metadata:
      labels:
        app: portfolio-website
    spec:
      containers:
      - name: portfolio-website
        image: agonzaga/portfolio-website:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-website-service
  namespace: portfolio
spec:
  selector:
    app: portfolio-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 192.168.42.108
