# ====================================================================
# Stack: file-explorer
# Endpoint: VM-Media
# Source: Portainer stack ID 150 (portainer_dump\compose\150\docker-compose.yml)
# Generated: 2025-08-29 19:40:11
#
# What this does:
# - Docker Compose stack exported from Portainer.
# - Includes the following services (name : image):
#   - filebrowser : filebrowser/filebrowser:latest
#
# How to deploy:
# - Ensure any referenced volumes/networks exist.
# - Create/update a .env file if needed.
# - Run: docker compose up -d
# ====================================================================
version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8081:80"  # Access via http://<host>:8081
    volumes:
      - /mnt/storage:/srv           # Your actual storage path
      - filebrowser_config:/config  # Persistent config
    environment:
      - PUID=1000                   # Set to your user ID
      - PGID=1000                   # Set to your group ID
    restart: unless-stopped

volumes:
  filebrowser_config: