apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-kubernetes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Gnzaga/homelab-code.git
    targetRevision: master
    path: kubernetes
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

