# ====================================================================
# Stack: stable-diffusion
# Endpoint: endpoint-7
# Source: Portainer stack ID 23 (portainer_dump\compose\23\docker-compose.yml)
# Generated: 2025-08-29 19:40:08
#
# What this does:
# - Docker Compose stack exported from Portainer.
# - Includes the following services (name : image):
#   - stable-diffusion-webui : universonic/stable-diffusion-webui:minimal
#
# How to deploy:
# - Ensure any referenced volumes/networks exist.
# - Create/update a .env file if needed.
# - Run: docker compose up -d
# ====================================================================
version: "3.2"

services:
  stable-diffusion-webui:
    image: universonic/stable-diffusion-webui:minimal
    command: --no-half --no-half-vae --precision full
    runtime: nvidia
    restart: unless-stopped
    ports:
      - ${STABLE_DIFFUSION_WEBUI_PORT1}:8080/tcp
    volumes:
      - ${STABLE_DIFFUSION_WEBUI_PORT2}:/app/stable-diffusion-webui/inputs
      - ${STABLE_DIFFUSION_WEBUI_PORT3}:/app/stable-diffusion-webui/textual_inversion_templates
      - ${STABLE_DIFFUSION_WEBUI_PORT4}:/app/stable-diffusion-webui/embeddings
      - ${STABLE_DIFFUSION_WEBUI_PORT5}:/app/stable-diffusion-webui/extensions
      - ${STABLE_DIFFUSION_WEBUI_PORT6}:/app/stable-diffusion-webui/models
      - ${STABLE_DIFFUSION_WEBUI_PORT7}:/app/stable-diffusion-webui/localizations
      - ${STABLE_DIFFUSION_WEBUI_PORT8}:/app/stable-diffusion-webui/outputs
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.iface != extern"
      restart_policy:
        condition: unless-stopped
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
