# ====================================================================
# Stack: authetnik-deployment
# Endpoint: endpoint-19
# Source: Portainer stack ID 90 (portainer_dump\compose\90\docker-compose.yml)
# Generated: 2025-08-29 19:40:09
#
# What this does:
# - Docker Compose stack exported from Portainer.
# - Includes the following services (name : image):
#   - authentik : ghcr.io/goauthentik/server:latest
#   - authentik-db : postgres:15
#
# How to deploy:
# - Ensure any referenced volumes/networks exist.
# - Create/update a .env file if needed.
# - Run: docker compose up -d
# ====================================================================
version: '3.8'

services:
  authentik:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik
    environment:
      - AUTHENTIK_POSTGRESQL__HOST=authentik-db
      - AUTHENTIK_POSTGRESQL__USER=${AUTHENTIK_POSTGRESQL__USER}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_POSTGRESQL__PASSWORD}
      - AUTHENTIK_POSTGRESQL__NAME=authentik
    volumes:
      - ${AUTHENTIK_PORT1}:/config
    ports:
      - "9000:9000"  # Authentik web interface
    depends_on:
      - authentik-db
    restart: unless-stopped

  authentik-db:
    image: postgres:15
    container_name: authentik-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=authentik
    volumes:
      - ${AUTHENTIK_DB_PORT1}:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  authentik_data:
  authentik_db:
