# ====================================================================
# Stack: media-monitoring
# Endpoint: VM-Media
# Source: Portainer stack ID 119 (portainer_dump\compose\119\docker-compose.yml)
# Generated: 2025-08-29 19:40:11
#
# What this does:
# - Docker Compose stack exported from Portainer.
# - Includes the following services (name : image):
#   - dozzle : amir20/dozzle
#   - glances : nicolargo/glances:latest-full
#   - dashy : lissy93/dashy
#   - cadvisor : gcr.io/cadvisor/cadvisor:latest
#   - prometheus : prom/prometheus:latest
#   - grafana : grafana/grafana-oss
#
# How to deploy:
# - Ensure any referenced volumes/networks exist.
# - Create/update a .env file if needed.
# - Run: docker compose up -d
# ====================================================================
version: '3.8'

services:
  dozzle:
    image: amir20/dozzle
    container_name: dozzle
    ports:
      - ${DOZZLE_PORT1}:8080
    volumes:
      - ${DOZZLE_PORT2}:/var/run/docker.sock
    restart: unless-stopped

  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    ports:
      - ${GLANCES_PORT1}:61208
    volumes:
      - ${GLANCES_PORT2}:ro
    command: glances -w
    restart: unless-stopped

  dashy:
    image: lissy93/dashy
    container_name: dashy
    ports:
      - ${DASHY_PORT1}:80
    volumes:
      - ${DASHY_PORT2}:/app/public/conf.yml
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - ${CADVISOR_PORT1}:8080
    volumes:
      - ${CADVISOR_PORT2}:ro
      - ${CADVISOR_PORT3}:ro
      - ${CADVISOR_PORT4}:ro
      - ${CADVISOR_PORT5}:ro
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - ${PROMETHEUS_PORT1}:9090
    volumes:
      - ${PROMETHEUS_PORT2}:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - ${GRAFANA_PORT1}:3000
    volumes:
      - ${GRAFANA_PORT2}:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  grafana-storage:
